//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mongo.Migration.Exceptions {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorTexts {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorTexts() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Mongo.Migration.Exceptions.ErrorTexts", typeof(ErrorTexts).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string AlreadyInitialized {
            get {
                return ResourceManager.GetString("AlreadyInitialized", resourceCulture);
            }
        }
        
        public static string NoMongoClientRegistered {
            get {
                return ResourceManager.GetString("NoMongoClientRegistered", resourceCulture);
            }
        }
        
        public static string DuplicateVersion {
            get {
                return ResourceManager.GetString("DuplicateVersion", resourceCulture);
            }
        }
        
        public static string InvalidVersionValue {
            get {
                return ResourceManager.GetString("InvalidVersionValue", resourceCulture);
            }
        }
        
        public static string VersionStringToLong {
            get {
                return ResourceManager.GetString("VersionStringToLong", resourceCulture);
            }
        }
        
        public static string VersionViolated {
            get {
                return ResourceManager.GetString("VersionViolated", resourceCulture);
            }
        }
        
        public static string AppDirNotFound {
            get {
                return ResourceManager.GetString("AppDirNotFound", resourceCulture);
            }
        }
    }
}
